version: '3'

services:
  dev-mongo:
    image: mongo
    ports:
      - "27017:27017"

  flask-backend:
    build: backend
    ports:
      - "5000:5000"
    depends_on:
      - dev-mongo

  frontend:
    build: frontend
    ports:
      - "8080:80"
