name: Push Docker Image

on: 
  push:
    branches:
      - main 
    paths:
      - 'backend/**'
      - 'frontend/**'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/kube:backend-latest

      - name: Build and push Docker image frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/kube:frontend-latest